### ISSUE TITLE
deepbryo_tiny.pth is not a checkpoint file

### ISSUE THREAD

**Issue by meghalithic** [agporto/DeepBryo#3]
@agporto I tried running DeepBryo on my forked repo and got the error: "inference/deepbryo_tiny.pth is not a checkpoint file. I'm attaching screenshots from the web interface as well as the terminal that describe the error. I'm using ubuntu on linux. Thanks!
![Screenshot from 2024-06-07 14-05-12](https://github.com/agporto/DeepBryo/assets/6617332/5ede7a0e-31ce-4737-9cae-7d7736346c48)
![Screenshot from 2024-06-07 14-06-29](https://github.com/agporto/DeepBryo/assets/6617332/2ea4fbe7-da44-49ee-8f14-b75aeb2c65ae)

**Comment by agporto** [comment]
check that the file `inference/deepbryo_tiny.pth` is present. It is looking for it and not finding it (or something like it), according to your initial error.

**Comment by meghalithic** [comment]
Ah, that was silly. There is no folder called inferences, is that something I create? It seems that from the history Steginator already came with the folder.
